FROM crystallang/crystal:0.26.1

ARG dir_name="crystal_mfa"

ENV PATH=$PATH:/usr/local/go/bin 
ENV GOPATH=/go
ENV LUCKY_ENV=development
ENV DATABASE_URL=postgres://crystal.postgres/${dir_name}_development

COPY entry_point.sh /entry_point.sh

RUN apt-get update \
  && apt-get install -y curl wget npm postgresql libqrencode-dev \
  && npm install -g n yarn \
  && n stable \
  && wget -q https://storage.googleapis.com/golang/go1.10.1.linux-amd64.tar.gz \
  && tar -C /usr/local -xzf go1.10.1.linux-amd64.tar.gz \
  && go get github.com/DarthSim/overmind \
  && go get github.com/ddollar/forego \
  && wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh \
  && apt-get clean

RUN git clone https://github.com/luckyframework/lucky_cli \
  && cd lucky_cli \
  && git checkout refs/tags/v0.11.0 \
  && shards install \
  && crystal build src/lucky.cr --release --no-debug \
  && mv lucky /usr/local/bin

WORKDIR /${dir_name}

EXPOSE 3001

ENTRYPOINT  /entry_point.sh